# Site
name: "Azure Late Show Podcast"
title: "Azure Late Show Podcast"
description: "Embracing tech intensity to build your own digital capabilities"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: 'UA-152610368-1'
disqus: 'wikiazure'
mailchimp-list: 'https://wikiazure.us6.list-manage.com/subscribe/post?u=02b69fb6665744c97db5aad52&amp;id=6edade044c'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dave:
    name: Dave
    display_name: Dave    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: DaveRndn
    web: https://wikiazure.com/blog
    twitter: https://twitter.com/daverndn
    description: "Microsoft Azure MVP, embracing and fostering tech intensity to benefit society and thrive in a digital world."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
